version: '2'

services:
  vue_php:
    image: vueapp_vue_php
    build:
      context: ./app
      dockerfile: ./docker/prod/php/Dockerfile
    container_name: vue_php
    networks:
      - webgateway
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:vue.sa-php.indovti.com"
      - "traefik.backend=vue.sa-php"
      - "traefik.docker.network=webgateway"

  vue_java:
    image: vueapp_vue_java
    build:
      context: ./app
      dockerfile: ./docker/prod/java/Dockerfile
    container_name: vue_java
    networks:
      - webgateway
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:vue.sa-java.indovti.com"
      - "traefik.backend=vue.sa-java"
      - "traefik.docker.network=webgateway"

  vue_node:
    image: vueapp_vue_node
    build:
      context: ./app
      dockerfile: ./docker/prod/node/Dockerfile
    container_name: vue_node
    networks:
      - webgateway
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:vue.sa-node.indovti.com"
      - "traefik.backend=vue.sa-node"
      - "traefik.docker.network=webgateway"

networks:
  webgateway:
    external:
      name: webgateway
  web:
    external:
      name: traefik

